[package]
edition.workspace = true
name              = "vprogs-state-metadata"
version.workspace = true

[dependencies]
borsh.workspace                = true
vprogs-core-types.workspace    = true
vprogs-state-space.workspace   = true
vprogs-storage-types.workspace = true
